name: Generate Snake Contribution Grid

on:
  schedule:
    - cron: "0 0 * * *"  # يتم تشغيله يوميًا عند منتصف الليل
  workflow_dispatch:  # يتيح تشغيله يدويًا

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Generate Snake Animation
        uses: Platane/snk@v2
        with:
          github_user_name: aprahemmahmoud  # ✅ تأكد من صحة اسم المستخدم
          outputs: dist/github-snake.svg  # ✅ تبسيط الاسم

      - name: Upload Artifact
        uses: actions/upload-artifact@v4  # ✅ تحديث الإصدار
        with:
          name: snake-animation
          path: dist/github-snake.svg  # ✅ تأكد من صحة المسار
